### ISSUE TITLE
Scheduler 및 Transectional 충돌 오류

### ISSUE THREAD

**Issue by HyungJoonSon** [View-Pharm/YakAl#17]
I suppose there are several things happens:

UserServiceImpl is created.
@Scheduled annotation is processed and reference to bean is stored to invoke it at appropriate time.
@Transactional annotation is processed. It create proxy which store reference to original bean. Original bean is replaced to proxy in application context.
If step 2 and 3 passed in different order then you had no problem.

둘이 동기적으로 진행되면 상관 없지만, 두 어노테이션을 사용시 비동기적으로 작동하여 DB 오류가 생길 수 있습니다. 오류 수정 부탁드려요

**Comment by Shortood** [comment]
넵 수정하겠습니다
